export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const CREATE_ORDER ="CREATE_ORDER";
export const SORT_PRODUCTS ="SORT_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";